In [68]:
import numpy as np

In [69]:
states = [(a,b) for a in range(5) for b in range(5)]
actions = ['N','E','S','W']
rewards = [-2,-1,10]

In [70]:
def pi(a,s):
    if a == 'N':
        return 0.25
    elif a == 'S':
        return 0.25
    elif a == 'W':
        return 0.25
    else:
        return 0.25

In [71]:
def prob2(s_prime,r,s,a):

    if s in [(0,4),(1,2),(1,3),(1,4),(2,1),(2,2),(3,2)]:
        return 0.0
    if a == 'N':

        if s in [(2,4),(2,3),(4,2),(3,1)]:
            if s_prime == s and r == -2:
                return 1.0
            else:
                return 0.0

        elif s[0] > 0 and s_prime == (s[0]-1,s[1]) and r == -1:
            return 1.0
        elif s[0] == 0 and s_prime == s and r==-1:
            return 1.0
        else:
            return 0.0

    elif a == 'W':

        if s in [(2,3),(3,3)]:
            if s_prime == s and r == -2:
                return 1.0
            else:
                return 0.0
        elif s[1] > 0 and s_prime == (s[0],s[1]-1) and r == -1:
            return 1.0
        elif s[1] == 0 and s_prime == s and r == -1:
            return 1.0
        else:
            return 0.0

    elif a == 'S':

        if s in [(1,1),(0,2),(0,3),(0,4)]:
            if s_prime == s and r == -2:
                return 1.0
            else:
                return 0.0

        if s[0] < 4 and s_prime == (s[0]+1,s[1]) and r == -1:
            return 1.0
        elif s[0] == 4 and s_prime == s and r==-1:
            return 1.0
        else:
            return 0.0

    elif a == 'E':

#         if s == [0,3]:
#             if s_prime == [0,4] and r == 9:
#                 return 1.0
#             else: return 0.0

        if s in [(1,1),(2,0),(3,1)]:
            if s_prime == s and r == -2:
                return 1.0
            else:
                return 0.0

        if s[1] < 4 and s_prime == (s[0],s[1]+1) and r == -1:
            return 1.0
        elif s[1] == 4 and s_prime == s and r==-1:
            return 1.0
        else:
            return 0.0 

In [72]:
gamma = 1

In [73]:
def B(v):
    vector = np.array([np.sum([pi(a,s)*prob2(s_prime,r,s,a)*(r + gamma * v[states.index(s_prime)])\
                     for s_prime in states for a in actions for r in rewards]) for s in states])
    vector[states.index((0,4))] = 10
#     def w(s):
#         i = states.index(s)
#         if i == 4:
#             return 10
#         else:
#             return vector[i]
    
    return vector

In [74]:
v_0 = np.zeros(25)

In [75]:
eps = 1 
w = v_0
while eps > 0.0001:
    v = B(w)
    eps = (np.array([(v[states.index(s)] - w[states.index(s)])**2 for s in states ])).sum()
    w = v

In [76]:
v[states.index([0,1])]

ValueError: [0, 1] is not in list

In [77]:
for s in states:
    print(s,v[states.index(s)])

(0, 0) -260.9580813316363
(0, 1) -226.53220960960599
(0, 2) -152.6853817810218
(0, 3) -73.8418600104887
(0, 4) 10.0
(1, 0) -291.389647620823
(1, 1) -261.9580813316363
(1, 2) 0.0
(1, 3) 0.0
(1, 4) 0.0
(2, 0) -347.2591938786195
(2, 1) 0.0
(2, 2) 0.0
(2, 3) -521.1596791488599
(2, 4) -521.623884509359
(3, 0) -398.13652464441384
(3, 1) -422.07972679517616
(3, 2) 0.0
(3, 3) -514.7078067323284
(3, 4) -517.1004486776203
(4, 0) -421.07972679517616
(4, 1) -440.0325993224599
(4, 2) -472.94850997649263
(4, 3) -500.8754698541501
(4, 4) -510.98190959442206


In [78]:
val = v.reshape((5,5))
for row in val:
    print(row)


[-260.95808133 -226.53220961 -152.68538178  -73.84186001   10.        ]
[-291.38964762 -261.95808133    0.            0.            0.        ]
[-347.25919388    0.            0.         -521.15967915 -521.62388451]
[-398.13652464 -422.0797268     0.         -514.70780673 -517.10044868]
[-421.0797268  -440.03259932 -472.94850998 -500.87546985 -510.98190959]


In [79]:
policy = np.zeros(25)

In [80]:
while eps>0.000001:
    
    def q(s,a):
        return np.sum([prob2(s_prime,r,s,a)*(r + v[states.index(s_prime)]) for s_prime in states for r in rewards])
    
    new_v =  np.array([np.max([q(s,a) for a in actions]) for s in states]) 
    new_policy = np.array([actions[np.argmax([q(s,a) for a in actions])] for s in states]) 
    new_v[4] = 10
    eps = np.sum((v - new_v)**2)
    policy = new_policy
    v = new_v
    print(eps)

30285.92971403633
37051.73064963819
39155.3602295812
37328.38732462219
29454.50296026766
34790.69152404078
37750.5024349192
36450.627172562265
25206.72707208556
26636.503196001686
30712.611083028733
31151.43562796112
19785.16142163427
6862.773769997407
0.0


In [81]:
val = v.reshape((5,5))
val

array([[ 6.,  7.,  8.,  9., 10.],
       [ 5.,  6.,  0.,  0.,  0.],
       [ 4.,  0.,  0., -3., -4.],
       [ 3.,  2.,  0., -2., -3.],
       [ 2.,  1.,  0., -1., -2.]])

In [82]:
policy.reshape((5,5))

array([['E', 'E', 'E', 'E', 'N'],
       ['N', 'N', 'N', 'N', 'N'],
       ['N', 'N', 'N', 'S', 'S'],
       ['N', 'W', 'N', 'S', 'S'],
       ['N', 'N', 'W', 'W', 'W']], dtype='<U1')

In [83]:
d = {'a':1,'b':2,'c':3,'d':4}

In [84]:
d['a']

1

In [92]:
a = d.values()
for x in a:
    print(x)

1
2
3
4


In [93]:
d['a']

1

In [94]:
a = [-1,-1,2,10]

In [96]:
list(set(a))

[2, 10, -1]

In [98]:
a = np.array(['X' for _ in range(25)])

In [99]:
a

array(['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X',
       'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
      dtype='<U1')

In [100]:
a.reshape((5,5))

array([['X', 'X', 'X', 'X', 'X'],
       ['X', 'X', 'X', 'X', 'X'],
       ['X', 'X', 'X', 'X', 'X'],
       ['X', 'X', 'X', 'X', 'X'],
       ['X', 'X', 'X', 'X', 'X']], dtype='<U1')